name: Usability question
description: Ask a usability-related question.
title: "[Use]: "
labels:
  - Usability
projects:
  - "NERC-EDS/7"

body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: A clear and concise description of your issue.
      placeholder: What do you need help with?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or supporting information (e.g. screenshots) about the problem here.
